use_frameworks!

target 'Knot_Example' do
  pod 'Knot', :path => '../'
  pod 'Texture'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'BonMot'
  
  target 'Knot_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
